import { Component } from '@angular/core';
import { NgbNavChangeEvent } from '@ng-bootstrap/ng-bootstrap';

const customessay = [
  {id: 1, name:'How can an Essay Writing Service help you write a college essay?', description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a euismod ipsum. Ut eu molestie justo, sed tempor purus. Suspendisse nunc nisl, ultricies sit amet neque non, posuere volutpat lacus. Etiam id maximus ligula. Ut nisl quam, iaculis quis lorem condimentum, sagittis pellentesque quam. Vivamus ornare, turpis ut laoreet mattis, ipsum enim efficitur eros, sit amet consectetur diam nulla ac mauris. Donec consequat ex at urna ullamcorper congue. Duis vitae luctus nisl. Curabitur eget vestibulum eros, eu facilisis leo. Fusce molestie velit augue, in laoreet eros dignissim non. Sed feugiat quam dolor, in tempor ante laoreet quis. Suspendisse lobortis, nulla a faucibus mollis, tortor purus aliquam mauris, sit amet tempor mi tortor eu justo. Aenean convallis nisi a ante posuere fringilla. Nam at nisi magna. In ut neque eu ante scelerisque sodales in vel sapien. Curabitur elementum elit quam.'},
  {id: 2, name:'What is a college essay?', description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a euismod ipsum. Ut eu molestie justo, sed tempor purus. Suspendisse nunc nisl, ultricies sit amet neque non, posuere volutpat lacus. Etiam id maximus ligula. Ut nisl quam, iaculis quis lorem condimentum, sagittis pellentesque quam. Vivamus ornare, turpis ut laoreet mattis, ipsum enim efficitur eros, sit amet consectetur diam nulla ac mauris. Donec consequat ex at urna ullamcorper congue. Duis vitae luctus nisl. Curabitur eget vestibulum eros, eu facilisis leo. Fusce molestie velit augue, in laoreet eros dignissim non. Sed feugiat quam dolor, in tempor ante laoreet quis. Suspendisse lobortis, nulla a faucibus mollis, tortor purus aliquam mauris, sit amet tempor mi tortor eu justo. Aenean convallis nisi a ante posuere fringilla. Nam at nisi magna. In ut neque eu ante scelerisque sodales in vel sapien. Curabitur elementum elit quam.'},
  {id: 3, name:'How to write a college essay?', description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a euismod ipsum. Ut eu molestie justo, sed tempor purus. Suspendisse nunc nisl, ultricies sit amet neque non, posuere volutpat lacus. Etiam id maximus ligula. Ut nisl quam, iaculis quis lorem condimentum, sagittis pellentesque quam. Vivamus ornare, turpis ut laoreet mattis, ipsum enim efficitur eros, sit amet consectetur diam nulla ac mauris. Donec consequat ex at urna ullamcorper congue. Duis vitae luctus nisl. Curabitur eget vestibulum eros, eu facilisis leo. Fusce molestie velit augue, in laoreet eros dignissim non. Sed feugiat quam dolor, in tempor ante laoreet quis. Suspendisse lobortis, nulla a faucibus mollis, tortor purus aliquam mauris, sit amet tempor mi tortor eu justo. Aenean convallis nisi a ante posuere fringilla. Nam at nisi magna. In ut neque eu ante scelerisque sodales in vel sapien. Curabitur elementum elit quam.'},
  {id: 4, name:'What should i write about in my college essay?', description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a euismod ipsum. Ut eu molestie justo, sed tempor purus. Suspendisse nunc nisl, ultricies sit amet neque non, posuere volutpat lacus. Etiam id maximus ligula. Ut nisl quam, iaculis quis lorem condimentum, sagittis pellentesque quam. Vivamus ornare, turpis ut laoreet mattis, ipsum enim efficitur eros, sit amet consectetur diam nulla ac mauris. Donec consequat ex at urna ullamcorper congue. Duis vitae luctus nisl. Curabitur eget vestibulum eros, eu facilisis leo. Fusce molestie velit augue, in laoreet eros dignissim non. Sed feugiat quam dolor, in tempor ante laoreet quis. Suspendisse lobortis, nulla a faucibus mollis, tortor purus aliquam mauris, sit amet tempor mi tortor eu justo. Aenean convallis nisi a ante posuere fringilla. Nam at nisi magna. In ut neque eu ante scelerisque sodales in vel sapien. Curabitur elementum elit quam.'},
  {id: 5, name:'What you should not write in a college essay?', description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a euismod ipsum. Ut eu molestie justo, sed tempor purus. Suspendisse nunc nisl, ultricies sit amet neque non, posuere volutpat lacus. Etiam id maximus ligula. Ut nisl quam, iaculis quis lorem condimentum, sagittis pellentesque quam. Vivamus ornare, turpis ut laoreet mattis, ipsum enim efficitur eros, sit amet consectetur diam nulla ac mauris. Donec consequat ex at urna ullamcorper congue. Duis vitae luctus nisl. Curabitur eget vestibulum eros, eu facilisis leo. Fusce molestie velit augue, in laoreet eros dignissim non. Sed feugiat quam dolor, in tempor ante laoreet quis. Suspendisse lobortis, nulla a faucibus mollis, tortor purus aliquam mauris, sit amet tempor mi tortor eu justo. Aenean convallis nisi a ante posuere fringilla. Nam at nisi magna. In ut neque eu ante scelerisque sodales in vel sapien. Curabitur elementum elit quam.'},
  {id: 6, name:'College essay tips to write a strong essay', description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a euismod ipsum. Ut eu molestie justo, sed tempor purus. Suspendisse nunc nisl, ultricies sit amet neque non, posuere volutpat lacus. Etiam id maximus ligula. Ut nisl quam, iaculis quis lorem condimentum, sagittis pellentesque quam. Vivamus ornare, turpis ut laoreet mattis, ipsum enim efficitur eros, sit amet consectetur diam nulla ac mauris. Donec consequat ex at urna ullamcorper congue. Duis vitae luctus nisl. Curabitur eget vestibulum eros, eu facilisis leo. Fusce molestie velit augue, in laoreet eros dignissim non. Sed feugiat quam dolor, in tempor ante laoreet quis. Suspendisse lobortis, nulla a faucibus mollis, tortor purus aliquam mauris, sit amet tempor mi tortor eu justo. Aenean convallis nisi a ante posuere fringilla. Nam at nisi magna. In ut neque eu ante scelerisque sodales in vel sapien. Curabitur elementum elit quam.'},
  {id: 7, name:'‘Write my college essay for me’ Help - 100% original and affordable', description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a euismod ipsum. Ut eu molestie justo, sed tempor purus. Suspendisse nunc nisl, ultricies sit amet neque non, posuere volutpat lacus. Etiam id maximus ligula. Ut nisl quam, iaculis quis lorem condimentum, sagittis pellentesque quam. Vivamus ornare, turpis ut laoreet mattis, ipsum enim efficitur eros, sit amet consectetur diam nulla ac mauris. Donec consequat ex at urna ullamcorper congue. Duis vitae luctus nisl. Curabitur eget vestibulum eros, eu facilisis leo. Fusce molestie velit augue, in laoreet eros dignissim non. Sed feugiat quam dolor, in tempor ante laoreet quis. Suspendisse lobortis, nulla a faucibus mollis, tortor purus aliquam mauris, sit amet tempor mi tortor eu justo. Aenean convallis nisi a ante posuere fringilla. Nam at nisi magna. In ut neque eu ante scelerisque sodales in vel sapien. Curabitur elementum elit quam.'},
  {id: 8, name:'‘College Essay tips', description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a euismod ipsum. Ut eu molestie justo, sed tempor purus. Suspendisse nunc nisl, ultricies sit amet neque non, posuere volutpat lacus. Etiam id maximus ligula. Ut nisl quam, iaculis quis lorem condimentum, sagittis pellentesque quam. Vivamus ornare, turpis ut laoreet mattis, ipsum enim efficitur eros, sit amet consectetur diam nulla ac mauris. Donec consequat ex at urna ullamcorper congue. Duis vitae luctus nisl. Curabitur eget vestibulum eros, eu facilisis leo. Fusce molestie velit augue, in laoreet eros dignissim non. Sed feugiat quam dolor, in tempor ante laoreet quis. Suspendisse lobortis, nulla a faucibus mollis, tortor purus aliquam mauris, sit amet tempor mi tortor eu justo. Aenean convallis nisi a ante posuere fringilla. Nam at nisi magna. In ut neque eu ante scelerisque sodales in vel sapien. Curabitur elementum elit quam.'},
  {id: 9, name:'‘College Essay Tips 2', description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a euismod ipsum. Ut eu molestie justo, sed tempor purus. Suspendisse nunc nisl, ultricies sit amet neque non, posuere volutpat lacus. Etiam id maximus ligula. Ut nisl quam, iaculis quis lorem condimentum, sagittis pellentesque quam. Vivamus ornare, turpis ut laoreet mattis, ipsum enim efficitur eros, sit amet consectetur diam nulla ac mauris. Donec consequat ex at urna ullamcorper congue. Duis vitae luctus nisl. Curabitur eget vestibulum eros, eu facilisis leo. Fusce molestie velit augue, in laoreet eros dignissim non. Sed feugiat quam dolor, in tempor ante laoreet quis. Suspendisse lobortis, nulla a faucibus mollis, tortor purus aliquam mauris, sit amet tempor mi tortor eu justo. Aenean convallis nisi a ante posuere fringilla. Nam at nisi magna. In ut neque eu ante scelerisque sodales in vel sapien. Curabitur elementum elit quam.'}
];
@Component({
  selector: 'app-customessay',
  templateUrl: './customessay.component.html',
  styleUrls: ['./customessay.component.css'] 
})
  

export class CustomessayComponent {
  cslist = customessay;
  active:any; 

}
